export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOGOUT_USER = "LOGOUT_USER";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";

export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

export const ADD_USERSID_FAVORITE = "ADD_USERSID_FAVORITE";

export const SET_POPOVER_VALUE = "SET_POPOVER_VALUE";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const SET_LIMIT_CARDS_ONPAGE = "SET_LIMIT_CARDS_ONPAGE";

